export const EXT_UPDATE = 'ext_update'
export const EXT_UPDATE_DONE = 'ext_update_done'
export const ENABLE_ALL_EXTENSION = 'enable_all_extension'
export const AC_FAVORITE = 'ac_favorite'
export const AC_RECENTLY_OPEN = 'ac_recently_open'
export const AC_ICON_UPDATED = 'ac_icon_updated'